# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tYnY13_QyxDm4GmOht8wHfSq2WEQHL8j
"""

!pip install streamlit



import streamlit as st

st.title('Uber pickups in NYC')