# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z2b7F8Hhzxu7lVj24BmmQf4rvRQd4eLJ
"""

import streamlit as st
from pysus.online_data.SIA import download

def teste_de_download(): 
  bi, ps = download('AC', 2020, 3, group=["BI", "PS"])
  novo = bi.head()
  st.write(novo)

if st.button('Botão de teste'):
    teste_de_download()